Repository growth-more/gomo-server, pull requests merged in 2025-09, with the labels that each got.

#72 [GOMO-197] 서버 모니터링을 위한 Acutator 적용
  build.gradle
Labels: enhancement

#76 [GOMO-198] Prometheus 의존성 추가
  build.gradle
Labels: documentation

#80 [GOMO-208] 시뮬레이션 테스트 API 추가
  build.gradle
  src/main/java/com/gomo/app/auth/application/OAuthUseCase.java
  src/main/java/com/gomo/app/auth/application/RefreshTokenUseCase.java
  src/main/java/com/gomo/app/common/configuration/SwaggerConfiguration.java
  src/main/java/com/gomo/app/diagnositc/LogSimulator.java
  src/main/java/com/gomo/app/logging/AuditLoggingAspect.java
  src/main/java/com/gomo/app/logging/LoggingFilter.java
  src/main/java/com/gomo/app/member/domain/model/Password.java
  src/main/resources/log4j2-spring.xml
Labels: enhancement, refactoring

#81 [GOMO-214] Flyway 도입
  build.gradle
  src/main/resources/database/data.sql
  src/main/resources/database/schema.sql
  src/main/resources/db/migration/V1__baseline.sql
  src/main/resources/db/migration/V2__insert_initial_policy_data.sql
  src/test/java/com/gomo/app/common/DatabaseContainerInitializer.java
  src/test/resources/database/sql/member-cleanup.sql
  src/test/resources/database/test-schema.sql
Labels: enhancement
