Repository growth-more/gomo-server, pull requests merged in 2025-04, with the labels that each got.

#31 [GOMO-90] 회원 기능 관련 테스트 보완 - 사용하지 않는 Import 삭제
  src/main/java/com/gomo/app/member/application/RefreshAccessTokenUseCase.java
  src/main/java/com/gomo/app/member/application/UpdateMemberUseCase.java
Labels: bug

#32 [GOMO-105] 멤버 수정기능 보완
  src/main/java/com/gomo/app/member/domain/model/MemberName.java
  src/main/java/com/gomo/app/member/domain/model/Motto.java
  src/test/java/com/gomo/app/member/unit/domain/MemberNameTest.java
  src/test/java/com/gomo/app/member/unit/domain/MottoTest.java
Labels: enhancement, refactoring

#33 [GOMO-83] 할당 퀘스트 수정 및 삭제 기능 수정
  src/main/java/com/gomo/app/quest/application/DeleteAssignQuestUseCase.java
  src/main/java/com/gomo/app/quest/application/UpdateAssignQuestUseCase.java
  src/main/java/com/gomo/app/quest/domain/model/AssignQuest.java
  src/test/java/com/gomo/app/member/integration/MemberRepositoryTest.java
  src/test/java/com/gomo/app/quest/common/fixture/AssignQuestFixture.java
  src/test/java/com/gomo/app/quest/unit/domain/AssignQuestTest.java
  src/test/java/com/gomo/app/quest/unit/usecase/DeleteAssignQuestUseCaseTest.java
  src/test/java/com/gomo/app/quest/unit/usecase/UpdateAssignQuestUseCaseTest.java
  src/test/resources/database/test-schema.sql
Labels: refactoring

#34 [GOMO-110] 관심사 조회 스펙 변경
  src/main/java/com/gomo/app/interest/application/ReadInterestNetworkUseCase.java
  src/main/java/com/gomo/app/interest/application/ReadInterestUseCase.java
  src/main/java/com/gomo/app/interest/domain/repository/MajorInterestRepository.java
  src/main/java/com/gomo/app/interest/presentation/response/ReadInterestResponse.java
  src/test/java/com/gomo/app/interest/documentation/snippet/InterestNetworkSnippet.java
  src/test/java/com/gomo/app/interest/documentation/snippet/ListInterestSnippet.java
  src/test/java/com/gomo/app/interest/documentation/snippet/ReadInterestSnippet.java
  src/test/java/com/gomo/app/interest/integration/MajorInterestRepositoryTest.java
  src/test/java/com/gomo/app/interest/unit/usecase/ReadInterestNetworkUseCaseTest.java
  src/test/java/com/gomo/app/interest/unit/usecase/ReadInterestUseCaseTest.java
Labels: refactoring

#35 [GOMO-111] 주요 관심사 조회 스펙 변경
  src/main/java/com/gomo/app/interest/presentation/response/ReadMajorInterestResponse.java
  src/test/java/com/gomo/app/interest/documentation/snippet/ListMajorInterestSnippet.java
  src/test/java/com/gomo/app/interest/unit/usecase/ReadMajorInterestUseCaseTest.java
Labels: refactoring

#37 [GOMO-107] 새로운 도메인 적용
  src/main/java/com/gomo/app/common/configuration/FilterRegistrationConfiguration.java
Labels: refactoring

#38 [GOMO-103] OAuth 리팩토링 및 Provider 추가
  src/main/java/com/gomo/app/member/application/OAuthUseCase.java
  src/main/java/com/gomo/app/member/domain/model/LoginProvider.java
  src/main/java/com/gomo/app/member/domain/model/OAuthUserInfo.java
  src/main/java/com/gomo/app/member/infrastructure/oauth/OAuthProvider.java
  src/main/java/com/gomo/app/member/infrastructure/oauth/OAuthProviderFactory.java
  src/main/java/com/gomo/app/member/infrastructure/oauth/provider/GoogleOAuthProvider.java
  src/main/java/com/gomo/app/member/infrastructure/oauth/provider/KakaoOAuthProvider.java
  src/main/java/com/gomo/app/member/infrastructure/oauth/provider/NaverOAuthProvider.java
  src/main/java/com/gomo/app/member/presentation/LoginMemberApi.java
  src/main/java/com/gomo/app/member/presentation/OauthApi.java
  src/main/resources/database/schema.sql
  src/test/java/com/gomo/app/member/documentation/OAuthDocuementationTest.java
  src/test/java/com/gomo/app/member/unit/usecase/OAuthUseCaseTest.java
  src/test/resources/database/test-schema.sql
Labels: enhancement, refactoring

#40 [GOMO-112] 관심사 색상 코드 추가
  src/main/java/com/gomo/app/interest/application/CreateInterestUseCase.java
  src/main/java/com/gomo/app/interest/application/UpdateInterestUseCase.java
  src/main/java/com/gomo/app/interest/domain/model/Interest.java
  src/main/java/com/gomo/app/interest/presentation/InterestApi.java
  src/main/java/com/gomo/app/interest/presentation/request/CreateInterestRequest.java
  src/main/java/com/gomo/app/interest/presentation/request/UpdateInterestRequest.java
  src/main/java/com/gomo/app/quest/application/CreateAssignQuestUseCase.java
  src/main/java/com/gomo/app/quest/domain/service/AssignQuestService.java
  src/main/java/com/gomo/app/quest/domain/service/RepeatQuestService.java
  src/test/java/com/gomo/app/interest/common/fixture/InterestFixture.java
  src/test/java/com/gomo/app/interest/documentation/CreateInterestDocumentationTest.java
  src/test/java/com/gomo/app/interest/documentation/UpdateInterestDocumentationTest.java
  src/test/java/com/gomo/app/interest/documentation/snippet/UpdateInterestSnippet.java
  src/test/java/com/gomo/app/interest/unit/domain/InterestTest.java
  src/test/java/com/gomo/app/interest/unit/usecase/CreateInterestUseCaseTest.java
  src/test/java/com/gomo/app/interest/unit/usecase/UpdateInterestUseCaseTest.java
  src/test/resources/database/sql/interest-cleanup.sql
  src/test/resources/database/test-schema.sql
Labels: enhancement, refactoring

#41 [GOMO-108] DisplayOrder 변경 기능 수정
  src/main/java/com/gomo/app/common/domain/service/OrderChanger.java
  src/main/java/com/gomo/app/interest/application/OrderUpdateMajorInterestUseCase.java
  src/main/java/com/gomo/app/interest/presentation/request/OrderUpdateMajorInterestRequest.java
  src/main/java/com/gomo/app/interest/presentation/request/UpdateOrderRequest.java
  src/main/java/com/gomo/app/quest/application/OrderUpdateAssignQuestUseCase.java
  src/main/java/com/gomo/app/quest/application/OrderUpdateRepeatQuestUseCase.java
  src/main/java/com/gomo/app/quest/presentation/request/OrderUpdateAssignQuestRequest.java
  src/main/java/com/gomo/app/quest/presentation/request/OrderUpdateRepeatQuestRequest.java
  src/main/java/com/gomo/app/quest/presentation/request/UpdateOrderRequest.java
  src/test/java/com/gomo/app/common/unit/OrderChangerTest.java
  src/test/java/com/gomo/app/interest/documentation/OrderUpdateMajorInterestDocumentationTest.java
  src/test/java/com/gomo/app/interest/documentation/snippet/OrderUpdateMajorInterestSnippet.java
  src/test/java/com/gomo/app/interest/unit/usecase/OrderUpdateMajorInterestUseCaseTest.java
  src/test/java/com/gomo/app/quest/documentation/OrderUpdateAssignQuestDocumentationTest.java
  src/test/java/com/gomo/app/quest/documentation/OrderUpdateRepeatQuestDocumentationTest.java
  src/test/java/com/gomo/app/quest/documentation/snippet/OrderUpdateAssignQuestSnippet.java
  src/test/java/com/gomo/app/quest/documentation/snippet/OrderUpdateRepeatQuestSnippet.java
  src/test/java/com/gomo/app/quest/unit/usecase/OrderUpdateAssignQuestUseCaseTest.java
  src/test/java/com/gomo/app/quest/unit/usecase/OrderUpdateRepeatQuestUseCaseTest.java
Labels: refactoring

#44 [GOMO-142] 이미지 처리 로직 수정
  src/main/java/com/gomo/app/interest/application/CreateInterestUseCase.java
  src/main/java/com/gomo/app/interest/application/DeleteInterestUseCase.java
  src/main/java/com/gomo/app/interest/application/UpdateLogoUseCase.java
  src/main/java/com/gomo/app/interest/domain/model/Interest.java
  src/main/java/com/gomo/app/interest/domain/model/Logo.java
  src/main/java/com/gomo/app/interest/domain/repository/InterestRepository.java
  src/main/java/com/gomo/app/interest/presentation/InterestApi.java
  src/main/java/com/gomo/app/interest/presentation/InterestLogoApi.java
  src/main/java/com/gomo/app/interest/presentation/request/CreateInterestRequest.java
  src/main/java/com/gomo/app/interest/presentation/response/ReadInterestResponse.java
  src/main/java/com/gomo/app/interest/presentation/response/ReadMajorInterestResponse.java
  src/main/java/com/gomo/app/member/application/UpdateMemberUseCase.java
  src/main/java/com/gomo/app/member/application/UpdateProfileBannerUseCase.java
  src/main/java/com/gomo/app/member/application/UpdateProfileImageUseCase.java
  src/main/java/com/gomo/app/member/domain/model/ProfileBanner.java
  src/main/java/com/gomo/app/member/domain/model/ProfileImage.java
  src/main/java/com/gomo/app/member/presentation/ProfileBannerApi.java
  src/main/java/com/gomo/app/member/presentation/ProfileImageApi.java
  src/main/java/com/gomo/app/member/presentation/request/UpdateProfileBannerRequest.java
  src/main/java/com/gomo/app/member/presentation/request/UpdateProfileImageRequest.java
  src/test/java/com/gomo/app/interest/common/fixture/InterestFixture.java
  src/test/java/com/gomo/app/interest/documentation/CreateInterestDocumentationTest.java
  src/test/java/com/gomo/app/interest/documentation/InterestNetworkDocumentationTest.java
  src/test/java/com/gomo/app/interest/documentation/ListInterestDocumentationTest.java
  src/test/java/com/gomo/app/interest/documentation/ReadInterestDocumentationTest.java
  src/test/java/com/gomo/app/interest/unit/domain/InterestTest.java
  src/test/java/com/gomo/app/interest/unit/domain/LogoTest.java
  src/test/java/com/gomo/app/interest/unit/usecase/CreateInterestUseCaseTest.java
  src/test/java/com/gomo/app/interest/unit/usecase/ReadInterestNetworkUseCaseTest.java
  src/test/java/com/gomo/app/interest/unit/usecase/ReadInterestUseCaseTest.java
  src/test/java/com/gomo/app/interest/unit/usecase/UpdateLogoUseCaseTest.java
  src/test/java/com/gomo/app/member/unit/domain/MemberTest.java
  src/test/java/com/gomo/app/member/unit/domain/ProfileBannerTest.java
  src/test/java/com/gomo/app/member/unit/domain/ProfileImageTest.java
  src/test/java/com/gomo/app/member/unit/usecase/UpdateMemberUseCaseTest.java
  src/test/java/com/gomo/app/member/unit/usecase/UpdateProfileBannerUseCaseTest.java
  src/test/java/com/gomo/app/member/unit/usecase/UpdateProfileImageUseCaseTest.java
  src/test/resources/database/sql/member-cleanup.sql
  src/test/resources/database/test-schema.sql
Labels: refactoring

#46 [GOMO-109] 회원 구독 플랜에 따른 관심사 생성 개수 제한
  README.md
  src/main/java/com/gomo/app/interest/application/CreateInterestUseCase.java
  src/main/java/com/gomo/app/interest/application/translator/InterestQuotaTranslator.java
  src/main/java/com/gomo/app/interest/domain/model/InterestQuota.java
  src/main/java/com/gomo/app/interest/domain/model/Proficiency.java
  src/main/java/com/gomo/app/interest/domain/repository/InterestRepository.java
  src/main/java/com/gomo/app/interest/domain/service/InterestService.java
  src/main/java/com/gomo/app/interest/exception/InterestErrorCode.java
  src/main/java/com/gomo/app/interest/exception/InterestQuotaExceededException.java
  src/main/java/com/gomo/app/member/application/UpdateMemberUseCase.java
  src/main/java/com/gomo/app/member/domain/service/ReadMemberService.java
  src/test/java/com/gomo/app/interest/unit/domain/InterestQuotaTest.java
  src/test/java/com/gomo/app/interest/unit/domain/InterestServiceTest.java
  src/test/java/com/gomo/app/interest/unit/usecase/CreateInterestUseCaseTest.java
  src/test/java/com/gomo/app/interest/unit/usecase/InterestQuotaTranslatorTest.java
  src/test/java/com/gomo/app/member/common/fixture/MemberFixture.java
  src/test/java/com/gomo/app/member/unit/domain/ReadMemberServiceTest.java
Labels: bug, refactoring, test

#47 [GOMO-122] 개발 / 운영 환경 분리
  .github/workflows/cicd.yml
  src/main/java/com/gomo/app/common/configuration/FilterRegistrationConfiguration.java
Labels: enhancement

#48 [GOMO-141] 데이터베이스 스키마 수정
  src/main/java/com/gomo/app/point/domain/model/PointWallet.java
  src/main/java/com/gomo/app/point/exception/PointWalletErrorCode.java
  src/main/java/com/gomo/app/streak/domain/model/Streak.java
  src/main/java/com/gomo/app/streak/exception/StreakErrorCode.java
  src/main/java/com/gomo/app/streak/exception/StreakUpdateFailureException.java
  src/main/resources/database/data.sql
  src/main/resources/database/schema.sql
Labels: refactoring

#49 [GOMO-153] 환경 분리 관련 workflow 경로 오류 수정
  .github/workflows/cicd.yml
Labels: bug
