Repository growth-more/gomo-server, pull requests merged in 2025-02, with the labels that each got.

#9 [GOMO-51] 스트릭 기능 구현
  build.gradle
  src/main/java/com/gomo/app/GomoApplication.java
  src/main/java/com/gomo/app/common/configuration/AuditConfiguration.java
  src/main/java/com/gomo/app/common/configuration/RetryConfiguration.java
  src/main/java/com/gomo/app/quest/exception/AssignQuestErrorCode.java
  src/main/java/com/gomo/app/quest/exception/RepeatQuestErrorCode.java
  src/main/java/com/gomo/app/streak/application/ReadStreakUseCase.java
  src/main/java/com/gomo/app/streak/domain/model/Streak.java
  src/main/java/com/gomo/app/streak/domain/repository/StreakRepository.java
  src/main/java/com/gomo/app/streak/domain/service/StreakService.java
  src/main/java/com/gomo/app/streak/event/CreateStreakHandler.java
  src/main/java/com/gomo/app/streak/exception/StreakErrorCode.java
  src/main/java/com/gomo/app/streak/exception/StreakUpdateFailureException.java
  src/main/java/com/gomo/app/streak/presentation/StreakApi.java
  src/main/java/com/gomo/app/streak/presentation/response/ListStreakResponse.java
  src/main/java/com/gomo/app/streak/presentation/response/ReadStreakResponse.java
  src/test/java/com/gomo/app/interest/common/constant/InterestFieldName.java
  src/test/java/com/gomo/app/interest/common/constant/MajorInterestFieldName.java
  src/test/java/com/gomo/app/interest/unit/domain/InterestTest.java
  src/test/java/com/gomo/app/interest/unit/domain/MajorInterestTest.java
  src/test/java/com/gomo/app/quest/common/constant/NonExistQuestField.java
  src/test/java/com/gomo/app/quest/common/dataprovider/AssignQuestDataProvider.java
  src/test/java/com/gomo/app/streak/common/dataprovider/StreakDataProvider.java
  src/test/java/com/gomo/app/streak/common/fixture/StreakFixture.java
  src/test/java/com/gomo/app/streak/documentation/ListStreakDocumentationTest.java
  src/test/java/com/gomo/app/streak/documentation/snippet/ListStreakSnippet.java
  src/test/java/com/gomo/app/streak/integration/StreakConflictTest.java
  src/test/java/com/gomo/app/streak/integration/StreakServiceTest.java
  src/test/java/com/gomo/app/streak/unit/domain/StreakTest.java
  src/test/java/com/gomo/app/streak/unit/usecase/ReadStreakUseCaseTest.java
  src/test/resources/database/sql/streak-cleanup.sql
  src/test/resources/database/test-schema.sql
Labels: enhancement

#10 [GOMO-52] 숙련도 및 관심사 관계 기능 구현
  src/main/java/com/gomo/app/interest/application/CreateInterestRelationUseCase.java
  src/main/java/com/gomo/app/interest/application/CreateMajorInterestUseCase.java
  src/main/java/com/gomo/app/interest/domain/model/ChildInterestId.java
  src/main/java/com/gomo/app/interest/domain/model/Interest.java
  src/main/java/com/gomo/app/interest/domain/model/ParentInterestId.java
  src/main/java/com/gomo/app/interest/domain/model/Proficiency.java
  src/main/java/com/gomo/app/interest/domain/model/Score.java
  src/main/java/com/gomo/app/interest/domain/model/ScoreThreshold.java
  src/main/java/com/gomo/app/interest/domain/repository/InterestRelationRepository.java
  src/main/java/com/gomo/app/interest/domain/repository/MajorInterestRepository.java
  src/main/java/com/gomo/app/interest/domain/service/InterestRelationService.java
  src/main/java/com/gomo/app/interest/domain/service/MajorInterestService.java
  src/main/java/com/gomo/app/interest/domain/service/ProficiencyService.java
  src/main/java/com/gomo/app/interest/domain/service/ScoreThresholdService.java
  src/main/java/com/gomo/app/interest/event/EnhanceProficiencyHandler.java
  src/main/java/com/gomo/app/interest/exception/InterestErrorCode.java
  src/main/java/com/gomo/app/interest/exception/InterestRelationCycleException.java
  src/main/java/com/gomo/app/interest/exception/InterestRelationDuplicatedException.java
  src/main/java/com/gomo/app/interest/exception/InterestRelationErrorCode.java
  src/main/java/com/gomo/app/interest/exception/MajorInterestErrorCode.java
  src/main/java/com/gomo/app/interest/exception/ProficiencyAdjustFailureException.java
  src/main/java/com/gomo/app/interest/presentation/response/ReadInterestResponse.java
  src/main/java/com/gomo/app/quest/application/CompleteAssignQuestUseCase.java
  src/main/java/com/gomo/app/quest/domain/model/AssignQuest.java
  src/main/java/com/gomo/app/quest/domain/repository/RepeatQuestRepository.java
  src/main/java/com/gomo/app/quest/domain/service/RepeatQuestService.java
  src/main/resources/database/data.sql
  src/test/java/com/gomo/app/interest/common/dataprovider/InterestRelationDataProvider.java
  src/test/java/com/gomo/app/interest/common/dataprovider/ScoreThresholdDataProvider.java
  src/test/java/com/gomo/app/interest/documentation/DeleteInterestRelationDocumentationTest.java
  src/test/java/com/gomo/app/interest/documentation/InterestNetworkDocumentationTest.java
  src/test/java/com/gomo/app/interest/documentation/snippet/InterestNetworkSnippet.java
  src/test/java/com/gomo/app/interest/documentation/snippet/ListInterestSnippet.java
  src/test/java/com/gomo/app/interest/documentation/snippet/ReadInterestSnippet.java
  src/test/java/com/gomo/app/interest/integration/InterestRelationRepositoryTest.java
  src/test/java/com/gomo/app/interest/integration/InterestRelationServiceTest.java
  src/test/java/com/gomo/app/interest/integration/MajorInterestRepositoryTest.java
  src/test/java/com/gomo/app/interest/integration/ProficiencyConflictTest.java
  src/test/java/com/gomo/app/interest/integration/ProficiencyServiceTest.java
  src/test/java/com/gomo/app/interest/integration/ScoreThresholdServiceTest.java
  src/test/java/com/gomo/app/interest/unit/domain/InterestTest.java
  src/test/java/com/gomo/app/interest/unit/domain/MajorInterestServiceTest.java
  src/test/java/com/gomo/app/interest/unit/domain/ProficiencyTest.java
  src/test/java/com/gomo/app/interest/unit/usecase/CreateInterestRelationUseCaseTest.java
  src/test/java/com/gomo/app/interest/unit/usecase/CreateMajorInterestUseCaseTest.java
  src/test/java/com/gomo/app/quest/integration/RepeatQuestRepositoryTest.java
  src/test/java/com/gomo/app/quest/unit/domain/AssignQuestTest.java
  src/test/java/com/gomo/app/quest/unit/domain/RepeatQuestServiceTest.java
  src/test/java/com/gomo/app/quest/unit/usecase/CompleteAssignQuestUseCaseTest.java
  src/test/resources/database/sql/interest-cleanup.sql
  src/test/resources/database/test-schema.sql
Labels: bug, enhancement

#12 [GOMO-54] 퀘스트 자동 생성 기능 구현
  src/main/java/com/gomo/app/common/configuration/ScheduleConfiguration.java
  src/main/java/com/gomo/app/common/domain/AuditorAwareImpl.java
  src/main/java/com/gomo/app/member/domain/model/DailyThreshold.java
  src/main/java/com/gomo/app/member/domain/model/Member.java
  src/main/java/com/gomo/app/member/domain/repository/MemberRepository.java
  src/main/java/com/gomo/app/quest/domain/repository/RepeatQuestRepository.java
  src/main/java/com/gomo/app/quest/domain/service/AssignQuestService.java
  src/main/java/com/gomo/app/quest/domain/service/ScheduleAssignQuestService.java
  src/main/resources/database/data.sql
  src/test/java/com/gomo/app/common/fixture/TestMemberFixture.java
  src/test/java/com/gomo/app/member/common/fixture/MemberFixture.java
  src/test/java/com/gomo/app/member/integration/MemberRepositoryTest.java
  src/test/java/com/gomo/app/quest/integration/ScheduleAssignQuestServiceTest.java
  src/test/java/com/gomo/app/streak/documentation/ListStreakDocumentationTest.java
  src/test/resources/database/sql/assign-quest-cleanup.sql
  src/test/resources/database/sql/interest-cleanup.sql
  src/test/resources/database/sql/interest-relation-cleanup.sql
  src/test/resources/database/sql/major-interest-cleanup.sql
  src/test/resources/database/sql/member-cleanup.sql
  src/test/resources/database/sql/point-cleanup.sql
  src/test/resources/database/sql/repeat-quest-cleanup.sql
  src/test/resources/database/sql/streak-cleanup.sql
  src/test/resources/database/test-schema.sql
Labels: enhancement

#13 [GOMO-56] 설문 기능 구현
  build.gradle
  src/main/java/com/gomo/app/common/util/UUIDConverter.java
  src/main/java/com/gomo/app/survey/application/CreateSurveyResultUseCase.java
  src/main/java/com/gomo/app/survey/application/ReadSurveyQuestionUseCase.java
  src/main/java/com/gomo/app/survey/domain/model/SurveyResult.java
  src/main/java/com/gomo/app/survey/domain/repository/SurveyItemRepository.java
  src/main/java/com/gomo/app/survey/domain/repository/SurveyResultRepository.java
  src/main/java/com/gomo/app/survey/exception/InvalidSurveyResultException.java
  src/main/java/com/gomo/app/survey/exception/SurveyResultErrorCode.java
  src/main/java/com/gomo/app/survey/infrastructure/SurveyResultRepositoryImpl.java
  src/main/java/com/gomo/app/survey/presentation/SurveyApi.java
  src/main/java/com/gomo/app/survey/presentation/request/CreateSurveyResultRequest.java
  src/main/java/com/gomo/app/survey/presentation/request/SelectedSurveyItem.java
  src/main/java/com/gomo/app/survey/presentation/response/ListSurveyQuestionResponse.java
  src/main/java/com/gomo/app/survey/presentation/response/ReadSurveyItemResponse.java
  src/main/java/com/gomo/app/survey/presentation/response/ReadSurveyQuestionResponse.java
  src/test/java/com/gomo/app/interest/unit/domain/InterestTest.java
  src/test/java/com/gomo/app/survey/common/dataprovider/SurveyItemDataProvider.java
  src/test/java/com/gomo/app/survey/common/dataprovider/SurveyQuestionDataProvider.java
  src/test/java/com/gomo/app/survey/common/fixture/SurveyItemFixture.java
  src/test/java/com/gomo/app/survey/common/fixture/SurveyQuestionFixture.java
  src/test/java/com/gomo/app/survey/common/util/SurveyResultDataHelper.java
  src/test/java/com/gomo/app/survey/documentation/CreateSurveyAnswerDocumentationTest.java
  src/test/java/com/gomo/app/survey/documentation/ListSurveyDocumentationTest.java
  src/test/java/com/gomo/app/survey/documentation/snippet/CreateSurveyAnswerSnippet.java
  src/test/java/com/gomo/app/survey/documentation/snippet/ListSurveySnippet.java
  src/test/java/com/gomo/app/survey/integration/SurveyResultRepositoryTest.java
  src/test/java/com/gomo/app/survey/unit/domain/SurveyResultTest.java
  src/test/java/com/gomo/app/survey/unit/usecase/CreateSurveyResultUseCaseTest.java
  src/test/java/com/gomo/app/survey/unit/usecase/ReadSurveyResultUseCaseTest.java
  src/test/resources/database/sql/survey-result-cleanup.sql
  src/test/resources/database/test-schema.sql
Labels: enhancement

#16 [GOMO-65] 관심사 도메인 리팩터링
  src/main/java/com/gomo/app/interest/domain/model/Level.java
  src/main/java/com/gomo/app/interest/domain/model/Proficiency.java
  src/main/java/com/gomo/app/interest/domain/model/ScoreThreshold.java
  src/main/java/com/gomo/app/interest/domain/model/ScoreThresholdPolicy.java
  src/main/java/com/gomo/app/interest/domain/repository/ScoreThresholdPolicyRepository.java
  src/main/java/com/gomo/app/interest/domain/repository/ScoreThresholdRepository.java
  src/main/java/com/gomo/app/interest/domain/service/ProficiencyService.java
  src/main/java/com/gomo/app/interest/domain/service/ScoreThresholdPolicyService.java
  src/main/java/com/gomo/app/interest/domain/service/ScoreThresholdService.java
  src/main/java/com/gomo/app/interest/infrastructure/ScoreThresholdPolicyRepositoryImpl.java
  src/main/java/com/gomo/app/interest/infrastructure/ScoreThresholdRepositoryImpl.java
  src/main/java/com/gomo/app/interest/presentation/response/ReadInterestResponse.java
  src/main/java/com/gomo/app/interest/presentation/response/ReadMajorInterestResponse.java
  src/main/resources/database/data.sql
  src/main/resources/database/schema.sql
  src/test/java/com/gomo/app/interest/common/dataprovider/ScoreThresholdDataProvider.java
  src/test/java/com/gomo/app/interest/integration/ProficiencyServiceTest.java
  src/test/java/com/gomo/app/interest/integration/ScoreThresholdPolicyRepositoryTest.java
  src/test/java/com/gomo/app/interest/integration/ScoreThresholdPolicyServiceTest.java
  src/test/java/com/gomo/app/interest/unit/domain/LevelTest.java
  src/test/resources/database/test-schema.sql
Labels: refactoring

#17 [GOMO-69] api 문서 최신화 및 기능 점검
  buildSrc/src/main/java/com/gomo/app/common/util/CommonUtils.java
  src/main/resources/static/swagger-ui/openapi3.json
  src/test/java/com/gomo/app/member/documentation/snippet/CheckDuplicatedHandleSnippet.java
Labels: documentation

#18 [GOMO-45] CI/CD 환경 세팅 및 Member 가입 기능 수정
  .github/workflows/cicd.yml
  .github/workflows/pr_notification.yml
  src/main/java/com/gomo/app/common/configuration/RedisConfiguration.java
  src/main/java/com/gomo/app/common/configuration/WebConfiguration.java
  src/main/java/com/gomo/app/member/application/CreateEmailAuthCodeUseCase.java
  src/main/java/com/gomo/app/member/application/CreateMemberUseCase.java
  src/main/resources/static/swagger-ui/openapi3.json
Labels: bug, enhancement, refactoring

#19 [GOMO-71] 이벤트 처리 구조 변경
  build.gradle
  src/main/java/com/gomo/app/common/configuration/RetryConfiguration.java
  src/main/java/com/gomo/app/common/event/Event.java
  src/main/java/com/gomo/app/common/event/EventConfiguration.java
  src/main/java/com/gomo/app/common/event/EventEntry.java
  src/main/java/com/gomo/app/common/event/EventEntryRepository.java
  src/main/java/com/gomo/app/common/event/EventHandler.java
  src/main/java/com/gomo/app/common/event/EventStatus.java
  src/main/java/com/gomo/app/common/event/Events.java
  src/main/java/com/gomo/app/common/util/JsonParser.java
  src/main/java/com/gomo/app/interest/domain/service/ProficiencyService.java
  src/main/java/com/gomo/app/interest/event/EnhanceProficiencyHandler.java
  src/main/java/com/gomo/app/member/application/CreateEmailAuthCodeUseCase.java
  src/main/java/com/gomo/app/point/domain/service/PointWalletService.java
  src/main/java/com/gomo/app/point/event/CompletedQuestPointHandler.java
  src/main/java/com/gomo/app/quest/application/CompleteAssignQuestUseCase.java
  src/main/java/com/gomo/app/quest/domain/model/PointReward.java
  src/main/java/com/gomo/app/quest/domain/model/ScoreReward.java
  src/main/java/com/gomo/app/quest/domain/service/QuestRewardService.java
  src/main/java/com/gomo/app/quest/event/PointQuestCompletedEvent.java
  src/main/java/com/gomo/app/quest/event/ScoreQuestCompletedEvent.java
  src/main/java/com/gomo/app/quest/event/StreakQuestCompletedEvent.java
  src/main/java/com/gomo/app/streak/domain/service/StreakService.java
  src/main/java/com/gomo/app/streak/event/CreateStreakHandler.java
  src/main/resources/database/schema.sql
  src/main/resources/static/swagger-ui/openapi3.json
  src/test/java/com/gomo/app/common/unit/JsonParserTest.java
  src/test/java/com/gomo/app/interest/integration/ProficiencyConflictTest.java
  src/test/java/com/gomo/app/member/unit/usecase/CreateMemberUseCaseTest.java
  src/test/java/com/gomo/app/point/integration/PointWalletConflictTest.java
  src/test/java/com/gomo/app/quest/integration/CompleteAssignQuestUseCaseTest.java
  src/test/java/com/gomo/app/quest/unit/domain/PointRewardTest.java
  src/test/java/com/gomo/app/quest/unit/domain/QuestRewardTest.java
  src/test/java/com/gomo/app/quest/unit/domain/ScoreRewardTest.java
  src/test/java/com/gomo/app/quest/unit/usecase/CompleteAssignQuestUseCaseTest.java
  src/test/java/com/gomo/app/streak/integration/StreakConflictTest.java
  src/test/resources/database/test-schema.sql
Labels: documentation, enhancement, refactoring

#20 [GOMO-79] 퀘스트 완료 기능 수정
  src/main/java/com/gomo/app/quest/domain/model/AssignQuest.java
  src/test/java/com/gomo/app/quest/unit/domain/AssignQuestTest.java
Labels: bug, refactoring

#22 [GOMO-78] 회원 가입 기능 로직 보완
  src/main/java/com/gomo/app/common/configuration/SMTPConfiguration.java
  src/main/java/com/gomo/app/member/application/CreateMemberUseCase.java
  src/main/java/com/gomo/app/member/domain/model/Handle.java
  src/test/java/com/gomo/app/member/unit/usecase/CreateMemberUseCaseTest.java
Labels: bug, enhancement, refactoring
