Repository growth-more/gomo-server, pull requests merged in 2025-08, with the labels that each got.

#63 [GOMO-168] 회원 탈퇴 로직 보완
  .github/workflows/cicd.yml
  src/main/java/com/gomo/app/common/configuration/AsyncConfig.java
  src/main/java/com/gomo/app/interest/domain/repository/InterestRelationRepository.java
  src/main/java/com/gomo/app/interest/domain/repository/InterestRepository.java
  src/main/java/com/gomo/app/interest/domain/repository/MajorInterestRepository.java
  src/main/java/com/gomo/app/interest/domain/service/InterestRelationService.java
  src/main/java/com/gomo/app/interest/domain/service/MajorInterestService.java
  src/main/java/com/gomo/app/member/application/DeleteMemberUseCase.java
  src/main/java/com/gomo/app/member/application/scheduler/MemberCleanupScheduler.java
  src/main/java/com/gomo/app/member/domain/model/Member.java
  src/main/java/com/gomo/app/member/domain/repository/MemberRepository.java
  src/main/java/com/gomo/app/member/domain/service/MemberService.java
  src/main/java/com/gomo/app/point/domain/repository/PointRepository.java
  src/main/java/com/gomo/app/point/domain/repository/PointWalletRepository.java
  src/main/java/com/gomo/app/quest/domain/repository/AssignQuestRepository.java
  src/main/java/com/gomo/app/quest/domain/repository/RepeatQuestRepository.java
  src/main/java/com/gomo/app/streak/domain/repository/AchieverRepository.java
  src/main/java/com/gomo/app/streak/domain/repository/StreakRepository.java
  src/main/java/com/gomo/app/streak/domain/service/StreakService.java
  src/test/java/com/gomo/app/interest/integration/InterestRelationRepositoryTest.java
  src/test/java/com/gomo/app/interest/integration/MajorInterestRepositoryTest.java
  src/test/java/com/gomo/app/interest/unit/domain/InterestServiceTest.java
  src/test/java/com/gomo/app/interest/unit/domain/MajorInterestServiceTest.java
  src/test/java/com/gomo/app/member/unit/domain/MemberServiceTest.java
  src/test/java/com/gomo/app/member/unit/usecase/DeleteMemberUseCaseTest.java
  src/test/java/com/gomo/app/point/integration/PointRepositoryTest.java
  src/test/java/com/gomo/app/point/unit/domain/PointServiceTest.java
  src/test/java/com/gomo/app/quest/integration/AssignQuestRepositoryTest.java
  src/test/java/com/gomo/app/quest/integration/RepeatQuestRepositoryTest.java
Labels: bug, enhancement, refactoring, test

#65 [GOMO-184] 캘린더 조회 기능 수정
  src/main/java/com/gomo/app/quest/application/CalendarReadAssignQuestUseCase.java
  src/main/java/com/gomo/app/quest/domain/model/AssignQuest.java
  src/main/java/com/gomo/app/quest/domain/repository/AssignQuestRepository.java
  src/main/java/com/gomo/app/quest/presentation/CalendarAssignQuestApi.java
  src/test/java/com/gomo/app/quest/documentation/CalendarAssignQuestDocumentationTest.java
  src/test/java/com/gomo/app/quest/documentation/snippet/CalendarAssignQuestSnippet.java
  src/test/java/com/gomo/app/quest/fixture/AssignQuestFixture.java
  src/test/java/com/gomo/app/quest/integration/AssignQuestRepositoryTest.java
  src/test/java/com/gomo/app/quest/unit/usecase/CalendarReadAssignQuestUseCaseTest.java
Labels: bug

#67 [GOMO-185] 퀘스트 자동 생성 기능 비활성화
  src/main/java/com/gomo/app/quest/application/scheduler/CreateAssignQuestScheduler.java
  src/main/resources/database/data.sql
Labels: refactoring

#68 [GOMO-193] 에러 코드 문서화
  src/docs/asciidoc/apis/auth-api.adoc
  src/docs/asciidoc/apis/interest-api.adoc
  src/docs/asciidoc/apis/member-api.adoc
  src/docs/asciidoc/apis/quest-api.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/gomo/app/interest/exception/code/MajorInterestErrorCode.java
Labels: documentation, refactoring

#71 [GOMO-199] 관심사 네트워크 응답 형식 수정
  src/main/java/com/gomo/app/interest/application/ReadInterestNetworkUseCase.java
  src/main/java/com/gomo/app/interest/application/ReadInterestUseCase.java
  src/main/java/com/gomo/app/interest/domain/repository/MajorInterestRepository.java
  src/main/java/com/gomo/app/interest/presentation/response/ReadInterestResponse.java
  src/test/java/com/gomo/app/interest/documentation/snippet/InterestNetworkSnippet.java
  src/test/java/com/gomo/app/interest/documentation/snippet/ListInterestSnippet.java
  src/test/java/com/gomo/app/interest/documentation/snippet/ReadInterestSnippet.java
  src/test/java/com/gomo/app/interest/integration/MajorInterestRepositoryTest.java
  src/test/java/com/gomo/app/interest/unit/usecase/ReadInterestNetworkUseCaseTest.java
  src/test/java/com/gomo/app/interest/unit/usecase/ReadInterestUseCaseTest.java
Labels: refactoring
