Repository growth-more/gomo-server, pull requests merged in 2025-03, with the labels that each got.

#23 [GOMO-88] 이미지 처리 로직 변경
  src/main/java/com/gomo/app/common/domain/service/ImageService.java
  src/main/java/com/gomo/app/common/util/ImageCleanupScheduler.java
  src/main/java/com/gomo/app/interest/application/UpdateInterestLogoUseCase.java
  src/main/java/com/gomo/app/interest/domain/repository/InterestRepository.java
  src/main/java/com/gomo/app/interest/domain/service/LogoService.java
  src/main/java/com/gomo/app/member/application/UpdateMemberUseCase.java
  src/main/java/com/gomo/app/member/domain/repository/MemberRepository.java
  src/main/java/com/gomo/app/member/domain/service/ProfileImageService.java
  src/main/resources/static/swagger-ui/openapi3.json
  src/test/java/com/gomo/app/member/unit/usecase/UpdateMemberUseCaseTest.java
Labels: bug, enhancement, refactoring

#25 [GOMO-94] 인증관련 CORS 문제 해결
  src/main/java/com/gomo/app/common/configuration/FilterRegistrationConfiguration.java
  src/main/java/com/gomo/app/common/configuration/WebConfiguration.java
Labels: bug, enhancement

#27 [GOMO-101] JWT 토큰 관련 로직 수정
  src/main/java/com/gomo/app/common/util/JwtUtil.java
  src/main/java/com/gomo/app/member/application/RefreshAccessTokenUseCase.java
Labels: bug, enhancement

#28 [GOMO-101] Refresh Token 발급 관련 오류 수정
  src/main/java/com/gomo/app/member/presentation/LoginMemberApi.java
Labels: bug

#29 [GOMO-58] 테스트 보완
  build.gradle
  src/main/java/com/gomo/app/common/event/EventEntry.java
  src/main/java/com/gomo/app/quest/domain/model/QuestHistory.java
  src/test/java/com/gomo/app/common/unit/DateRangeCalculatorTest.java
  src/test/java/com/gomo/app/common/unit/DisplayOrderTest.java
  src/test/java/com/gomo/app/common/unit/EventEntryTest.java
  src/test/java/com/gomo/app/common/unit/TimestampGeneratorTest.java
  src/test/java/com/gomo/app/common/unit/UUIDGeneratorTest.java
  src/test/java/com/gomo/app/point/unit/domain/BalanceTest.java
Labels: refactoring
